# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/kiosk.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 713)
        MainWindow.setMinimumSize(QtCore.QSize(3, 0))
        MainWindow.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(10, 0, 1000, 664))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setMinimumSize(QtCore.QSize(1000, 311))
        self.label.setMaximumSize(QtCore.QSize(761, 311))
        self.label.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/../resource/ombori_white4.png"))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.splitter_3)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.TouchScreenTest_Button = QtWidgets.QPushButton(self.splitter)
        self.TouchScreenTest_Button.setMinimumSize(QtCore.QSize(419, 70))
        self.TouchScreenTest_Button.setMaximumSize(QtCore.QSize(419, 70))
        self.TouchScreenTest_Button.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.TouchScreenTest_Button.setObjectName("TouchScreenTest_Button")
        self.networkTest_Button = QtWidgets.QPushButton(self.splitter)
        self.networkTest_Button.setMinimumSize(QtCore.QSize(419, 70))
        self.networkTest_Button.setMaximumSize(QtCore.QSize(419, 70))
        self.networkTest_Button.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.networkTest_Button.setObjectName("networkTest_Button")
        self.PrinterTest_button = QtWidgets.QPushButton(self.splitter)
        self.PrinterTest_button.setMinimumSize(QtCore.QSize(418, 70))
        self.PrinterTest_button.setMaximumSize(QtCore.QSize(418, 70))
        self.PrinterTest_button.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.PrinterTest_button.setObjectName("PrinterTest_button")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.exit_Button = QtWidgets.QPushButton(self.splitter_2)
        self.exit_Button.setMinimumSize(QtCore.QSize(89, 25))
        self.exit_Button.setMaximumSize(QtCore.QSize(89, 25))
        self.exit_Button.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.exit_Button.setObjectName("exit_Button")
        self.poweroff_Button = QtWidgets.QPushButton(self.splitter_2)
        self.poweroff_Button.setMinimumSize(QtCore.QSize(89, 25))
        self.poweroff_Button.setMaximumSize(QtCore.QSize(89, 25))
        self.poweroff_Button.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.poweroff_Button.setObjectName("poweroff_Button")
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TouchScreenTest_Button.setText(_translate("MainWindow", "Touch Screen \n"
"Test&&Calibrate"))
        self.networkTest_Button.setText(_translate("MainWindow", "Network Test"))
        self.PrinterTest_button.setText(_translate("MainWindow", "Printer Test"))
        self.exit_Button.setText(_translate("MainWindow", "Exit"))
        self.poweroff_Button.setText(_translate("MainWindow", "Poweroff"))
import resource_rc
